### ISSUE TITLE
Add Search and filter

### ISSUE THREAD

**Issue by NordinAlex** [AlexNordin-dev/manero-backend#9]
I have created Search and Filter, but it is not working as I expected 🤔.

**Comment by raihanmehran** [comment]
Hey @AlexNordin-dev can you assign me to work on this issue?

**Comment by NordinAlex** [comment]
Hello @raihanmehran,
Thank you for your offer to help. However, I regret to tell you that I cannot assign you to this project. This is because the project is part of a school assignment, which means I'm not allowed to seek help outside my group. I appreciate your interest, and many thanks for your understanding.

Best regards,
Alex

**Comment by raihanmehran** [comment]
Dear Alex,

Thank you for reaching out and providing clarification regarding the project. I completely understand and respect the rules regarding seeking external help for your school assignment. It's important to adhere to the guidelines set by your institution.

If you have any other questions or need assistance in the future that doesn't violate the assignment's rules, feel free to reach out. I'm here to help within the allowed scope.

Best regards,
Mehran
